import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const OLLAMA_HOST = process.env.OLLAMA_HOST || 'http://localhost:11434';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workingModelsPath = path.join(__dirname, 'working-models.json');

/**
 * Queries Ollama's show API to inspect model details and determine if it has vision capabilities.
 * @param {string} modelName - Name of the model.
 * @returns {Promise<boolean>} True if the model has vision capabilities.
 */
export async function isModelVisionCapable(modelName) {
  const lowerName = modelName.toLowerCase();
  
  // Fast check: if the name suggests vision, it's highly likely to be vision-capable.
  const nameSuggestsVision = lowerName.includes('vision') || 
                              lowerName.includes('llava') || 
                              lowerName.includes('bakllava') ||
                              lowerName.includes('-vl') || 
                              lowerName.includes('ocr');

  try {
    const response = await fetch(`${OLLAMA_HOST}/api/show`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ name: modelName })
    });
    
    if (!response.ok) {
      // If the API call fails, fallback to name-based check
      return nameSuggestsVision;
    }
    
    const data = await response.json();
    
    // Check capabilities field
    if (Array.isArray(data.capabilities) && data.capabilities.includes('vision')) {
      return true;
    }
    
    // Check families field inside details
    const families = data.details?.families || (data.details?.family ? [data.details.family] : []);
    if (families.some(f => {
      const lf = f.toLowerCase();
      return lf.includes('clip') || lf.includes('vision') || lf.includes('llava') || lf.includes('vl') || lf.includes('ocr');
    })) {
      return true;
    }

    // Check presence of projector info
    if (data.projector_info) {
      return true;
    }

    return nameSuggestsVision;
  } catch (error) {
    // Graceful error fallback: use name detection
    return nameSuggestsVision;
  }
}

/**
 * Queries Ollama's local tags to find all installed vision models.
 * @returns {Promise<Array<string>>} List of installed vision models.
 */
export async function getInstalledVisionModels() {
  try {
    // 1. Try to load the working-models.json list (generated by the tests)
    let workingModels = null;
    try {
      const fileContent = await fs.readFile(workingModelsPath, 'utf8');
      workingModels = JSON.parse(fileContent);
    } catch (e) {
      // File doesn't exist or is invalid, ignore
    }

    const response = await fetch(`${OLLAMA_HOST}/api/tags`);
    if (!response.ok) {
      throw new Error(`Failed to fetch tags: ${response.status}`);
    }
    
    const data = await response.json();
    const installedModels = (data.models || []).map(m => m.name);

    if (Array.isArray(workingModels)) {
      // Exclude any installed models that are not in the verified workingModels list
      return installedModels.filter(m => workingModels.includes(m));
    }
    
    // Query each model dynamically to check if it's vision-capable
    const visionChecks = await Promise.allSettled(
      installedModels.map(async (modelName) => {
        const isVision = await isModelVisionCapable(modelName);
        return { modelName, isVision };
      })
    );
    
    const visionModels = [];
    for (const result of visionChecks) {
      if (result.status === 'fulfilled' && result.value.isVision) {
        visionModels.push(result.value.modelName);
      }
    }

    return visionModels;
  } catch (error) {
    console.error('Error fetching installed vision models:', error.message);
    return [];
  }
}

/**
 * Queries Ollama's local tags to determine which vision model is installed.
 * @returns {Promise<string>} The model name to use.
 */
export async function getAvailableVisionModel() {
  try {
    const visionModels = await getInstalledVisionModels();
    console.log('Installed vision models in Ollama:', visionModels);

    if (visionModels.length === 0) {
      console.warn('No vision models detected in local Ollama. Defaulting to llava:latest.');
      return 'llava:latest';
    }

    // Prioritize models containing 'llava' (highly stable for this app)
    const llavaModel = visionModels.find(m => m.toLowerCase().includes('llava'));
    if (llavaModel) {
      console.log(`Auto-detected preferred vision model: ${llavaModel}`);
      return llavaModel;
    }

    // Second, prioritize models containing 'llama3.2-vision'
    const llamaVision = visionModels.find(m => m.toLowerCase().includes('llama3.2-vision'));
    if (llamaVision) {
      console.log(`Auto-detected vision model: ${llamaVision}`);
      return llamaVision;
    }

    // Otherwise, pick the first available vision model
    const firstModel = visionModels[0];
    console.log(`Auto-detected vision model: ${firstModel}`);
    return firstModel;
  } catch (error) {
    console.error('Error auto-detecting vision model, defaulting to llava:latest:', error.message);
    return 'llava:latest';
  }
}

/**
 * Analyzes a local image using an auto-detected Ollama vision model.
 * @param {string} filePath - Absolute path to the image file.
 * @returns {Promise<Object>} The parsed JSON analysis from the AI.
 */
export async function analyzeImage(filePath, selectedModel = null, keepAlive = null) {
  try {
    // 1. Read file and convert to base64
    const fileBuffer = await fs.readFile(filePath);
    const base64Image = fileBuffer.toString('base64');

    // 2. Auto-detect or use user selected model
    const activeModel = selectedModel || await getAvailableVisionModel();

    // 3. Prepare prompt
    const prompt = `Analyze this image (which might be low resolution, blurry, or poor quality) and suggest numerical adjustment values to enhance it.
    
You must return a JSON object. The response must follow this EXACT schema:
{
  "description": "A concise description of the scene and main objects depicted.",
  "flaws": [
    "List of visual quality issues found (e.g., 'low contrast', 'blurry', 'noise', 'chromatic aberration', 'incorrect white balance')"
  ],
  "adjustments": {
    "brightness": 0.0,  // Suggested brightness modifier. Range: -0.5 to 0.5 (0.0 is no change)
    "contrast": 1.0,    // Suggested contrast multiplier. Range: 0.5 to 2.0 (1.0 is no change)
    "saturation": 1.0,  // Suggested saturation multiplier. Range: 0.0 to 2.0 (1.0 is no change)
    "sharpness": 0.0,   // Suggested sharpening amount. Range: 0.0 to 5.0 (0.0 is no change)
    "denoise": false,   // Whether a denoise/blur operation is recommended
    "upscale": true,    // Whether upscaling is recommended
    "rotate": 0,        // Suggested rotation angle clockwise in degrees if the image is sideways or upside down. Allowed values: 0, 90, 180, 270 (0 is no change)
    "temperature": 1.0, // Suggested color temperature multiplier to correct white balance. Range: 0.5 to 1.5. (1.0 is no change, < 1.0 is cooler/blue, > 1.0 is warmer/orange)
    "tint": 1.0         // Suggested color tint multiplier to correct green/magenta casts. Range: 0.5 to 1.5. (1.0 is no change, < 1.0 is magenta/purple cast correction, > 1.0 is green cast correction)
  },
  "explanation": "A very brief explanation of why you recommended these specific parameters."
}

Do not include any text outside the JSON object. Do not include markdown code block syntax (like \`\`\`json).`;

    console.log(`Sending image ${filePath} to Ollama using model: ${activeModel}...`);
    
    // 4. Make HTTP request to local Ollama
    const requestBody = {
      model: activeModel,
      messages: [
        {
          role: 'user',
          content: prompt,
          images: [base64Image]
        }
      ],
      options: {
        temperature: 0.1
      },
      stream: false,
      format: 'json'
    };

    if (keepAlive !== null) {
      requestBody.keep_alive = keepAlive;
    }

    const response = await fetch(`${OLLAMA_HOST}/api/chat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Ollama API responded with status ${response.status}: ${errText}`);
    }

    const data = await response.json();
    const content = data.message?.content?.trim();

    if (!content) {
      throw new Error('Ollama returned an empty response.');
    }

    // 5. Parse the JSON result
    try {
      const parsedResult = JSON.parse(content);
      // Validate structure basics
      if (!parsedResult.adjustments) {
        parsedResult.adjustments = {
          brightness: 0.0,
          contrast: 1.0,
          saturation: 1.0,
          sharpness: 0.0,
          denoise: false,
          upscale: true,
          rotate: 0,
          temperature: 1.0,
          tint: 1.0
        };
      } else {
        if (parsedResult.adjustments.temperature === undefined) {
          parsedResult.adjustments.temperature = 1.0;
        }
        if (parsedResult.adjustments.tint === undefined) {
          parsedResult.adjustments.tint = 1.0;
        }
      }
      return parsedResult;
    } catch (parseError) {
      console.error('Failed to parse Ollama response as JSON. Content was:', content);
      throw new Error('AI output was not in the expected JSON format.');
    }

  } catch (error) {
    console.error('Ollama analysis error:', error);
    throw error;
  }
}
